// Generated by https://jsonformatter.org/json-to-typescript for Bundesliga api
export default interface Clubs {
  match_day_uids: string[];
  player: Player;
  scoring: Scoring;
  stats: Stats;
}

export interface Player {
  age: number;
  external_team_uid: string;
  external_uid: string;
  next_opponent: NextOpponent;
  nickname: string;
  past_attendances: unknown[];
  position: string;
  team: Team;
  uid: string;
  image_urls: ImageUrls;
}

export interface ImageUrls {
  default: string;
  "1x": string;
  "2x": string;
  "3x": string;
}

export interface NextOpponent {
  away_score: number;
  home_score: number;
  match_venue: string;
  starts_at: Date;
  team: Team;
}

export interface Team {
  external_uid: string;
  team_code: string;
  uid: string;
  image_urls?: ImageUrls;
}

export interface Scoring {
  entries: unknown[];
  total: number;
}

export interface Stats {
  form: number;
  last_match_points: number;
  popularity: number;
  transfer_value: number;
}
