// Generated by https://jsonformatter.org/json-to-typescript for https://gaming.uefa.com/en/uclpredictor/api/v1/competition/3/season/current/predictor/match_days
export default interface Result {
  data: Data_matchday;
}

export interface Data_matchday {
  items: CurrentMatchDay[];
  current_match_day: CurrentMatchDay;
}

export interface CurrentMatchDay {
  id: number;
  name: string;
  name_short: string;
  name_abbr: string;
  start_at: number;
  end_at: number;
  is_public: boolean;
  points_count_finished: boolean;
  predictable: boolean;
  has_played_match: boolean;
  related_match_number: number;
}
