// Generated by https://jsonformatter.org/json-to-typescript for https://gaming.uefa.com/en/eurofantasy/services/feeds/players/players_2_en_1.json
export default interface Result {
  data: Data;
  meta: Meta;
}

export interface Data {
  value: Value;
  feedTime: FeedTime;
}

export interface FeedTime {
  utcTime: string;
  istTime: string;
  cestTime: string;
}

export interface Value {
  playerList: PlayerList[];
}

export interface PlayerList {
  id: string;
  pDName: string;
  pDNameRu: string;
  pFName: string;
  latinName: string;
  tName: string;
  tId: string;
  teamPlayed: number;
  minsPlyd: number;
  mTransferIn: number;
  mTransferOut: number;
  rating: number;
  cCode: string;
  skill: number;
  value: number;
  isActive: number;
  selPer: number;
  mdId: string;
  totPts: number;
  gS: number;
  assist: number;
  cS: number;
  gC: number;
  yC: number;
  rC: number;
  oG: number;
  pS: number;
  pC: number;
  pE: number;
  saves: number;
  pM: number;
  bR: number;
  gOB: number;
  mOM: number;
  mOMPts: number;
  pStatus: PStatus;
  curGDPts: number;
  matchAtd: string;
  trained: Trained;
  isPlayed: number;
  selInPer: number;
  selOutPer: number;
  upcomingMatchesList: MatchesList[];
  currentMatchesList: MatchesList[];
  avgPlayerPts: number;
  avgPlayerValue: number;
  lastGdPoints: number;
  category1: number;
  category2: number;
  category3: number;
  category4: number;
  category5: number;
  category6: number;
  category7: number;
  category8: number;
  category9: number;
  category10: number;
  category11: number;
  category12: number;
  category13: number;
  category14: number;
  category15: number;
  dTotPts: number;
}

export interface MatchesList {
  mdId: string;
  tId: string;
  tSCode: string;
  cCode: string;
  tLoc: HomeAway;
  vsTID: string;
  vsTSCode: string;
  vsCCode: string;
  matchDate: string;
  vsTLoc: HomeAway;
}

export enum HomeAway {
  Away = "A",
  Home = "H",
}

export enum PStatus {
  D = "D",
  Empty = "",
  I = "I",
  Nis = "NIS",
  S = "S",
}

export enum Trained {
  DidNotTrain = "Did not train",
  Empty = "",
  InContentionToStartNextGame = "In contention to start next game",
  TookAFullPart = "Took a full part",
  UnlikelyToStartNextGame = "Unlikely to start next game",
}

export interface Meta {
  message: string;
  retVal: number;
  success: boolean;
  timestamp: FeedTime;
}
