name: Docker Build/Publish Beta

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: lukasdotcom/fantasy-manager
      DOCKER_TARGET_PLATFORM: linux/arm64,linux/amd64
    steps:
      - name: Checkout the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo "docker_platform=${DOCKER_TARGET_PLATFORM}" >> $GITHUB_OUTPUT
          echo "docker_image=${DOCKER_REGISTRY}/${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Run Buildx (push image)
        if: success()
        run: |
          docker buildx build --platform ${STEPS_PREPARE_OUTPUTS_DOCKER_PLATFORM} --tag ${STEPS_PREPARE_OUTPUTS_DOCKER_IMAGE}:nightly --file ./Dockerfile --push .
        env:
          STEPS_PREPARE_OUTPUTS_DOCKER_PLATFORM: ${{ steps.prepare.outputs.docker_platform }}
          STEPS_PREPARE_OUTPUTS_DOCKER_IMAGE: ${{ steps.prepare.outputs.docker_image }}
