name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      SQLITE: test.db
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24.x
          cache: "npm"
      # Installs packages
      - run: npm ci
      # Makes sure the code is formatted correctly
      - run: npm run pretty
      # Runs tests
      - run: npm run test:cli
      # Runs eslint
      - run: npm run lint
      # Builds the project
      - run: npm run build
      # Checks the db types
      - run: npm run dbtypes:check
